title: "Erik Renz"
tagline: "Digital Humanities · German Literary Studies"
description: "Personal academic website of Erik Renz"

url: "https://erre1998.github.io"
baseurl: ""

lang: "en"

markdown: kramdown

permalink: pretty

exclude:
  - README.md